#!/bin/bash
config_path="config.ini"
apt update && apt upgrade -y
apt install x11-apps -y
apt install libreoffice -y
apt install plocate -y
uno_paths=($(locate dist-packages/uno.py))
uno_path="${uno_paths[-1]}"
uno_dir="$(dirname "${uno_path}")"
echo -e "\nuno_path = $uno_dir" >> $config_path
